### ISSUE TITLE
Doorways need linking to partners

### ISSUE THREAD

**Issue by dodger101** [lil-kira/Java2D#9]

**Comment by kira0x1** [comment]
I loved you <3 

I cant believe all this time has passed... everythings fucked now. I miss you so much, I can barely handle it sometimes..
I wish you were still alive, still around... it feels like everything died too, i havent been the same since you died, and i dont think i ever will. everything's just... surface level, i dont love anything like I used to.. I just dont feel anything but frustration, and sometimes when I think about you and see an old project we worked on, and realize ill never be able to have those moments against with you, i feel something, i feel something horrible... i miss you so much i dont know what to do anymore, its so fucked i just want you back, and i cant handle it... its so bad now... everythings fucked now, i wish you were here to comfort me, and help me fall asleep, i wish i still had a person who took care of me, who could see through me, and know im not ok.
but it feels like ive had to take care of everyone else, everyones sad too, and i me telling them im at the edge just seem's useless. 
I just wished you were here, and wished i was able to be there for you. 
I loved you dodger
